routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::post('/reservation', 'ReservationController@reserve')->name('reservation.reserve');
Route::post('/contact', 'ContactController@sendMessage')->name('contact.send');


Route::group(['prefix'=>'admin','middleware'=>'auth','namespace'=>'Admin'], function () {
    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
    Route::resource('slider', 'SliderController');
    Route::resource('category', 'CategoryController');
    Route::resource('item', 'ItemController');
    Route::get('reservation', 'ReservationController@index')->name('reservation.index');
    Route::post('reservation/{id}', 'ReservationController@status')->name('reservation.status');
    Route::post('reject-reservation/{id}', 'ReservationController@inverseStatus')->name('reservation.inverseStatus');
    Route::delete('reservation/{id}', 'ReservationController@destroy')->name('reservation.destroy');

    Route::get('contact', 'ContactController@index')->name('contact.index');
    Route::get('contact/{id}', 'ContactController@show')->name('contact.show');
    Route::delete('contact/{id}', 'ContactController@destroy')->name('contact.destroy');
});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @method static find(int $id)
 */
class Slider extends Model
{
    //
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Slider;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders = Slider::all();
        return view('admin.slider.index', compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'sub_title' => 'required',
            'image' => 'required|mimes:png,jpeg,jpg,bmp,gif',
        ]);

        $image = $request->file('image');
        $slug = Str::slug($request->title);

        if (isset($image)){
            $currentDate = Carbon::now()->toDateString();
            $imagename = $slug .'-'. $currentDate .'-'. uniqid() .'.'. $image->getClientOriginalExtension();

            if (!file_exists('uploads/slider')){
                mkdir('uploads/slider', 0777, true);
            }
            $image->move('uploads/slider', $imagename);
        }else {
            $imagename = asset('assets/backend/img/Favicon.png');
        }

        $slider = new Slider();
        $slider->title = $request->title;
        $slider->sub_title = $request->sub_title;
        $slider->image = $imagename;
        $slider->save();
        return redirect(route('slider.index'))->with('successMsg', 'Slider Successfully Saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider = Slider::find($id);
        return view('admin.slider.edit', compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'sub_title' => 'required',
            'image' => 'image|mimes:png,jpeg,jpg,bmp,gif',
        ]);

        $image = $request->file('image');
        $slug = Str::slug($request->title);
        $slider = Slider::find($id);

        if (isset($image)){
            $currentDate = Carbon::now()->toDateString();
            $imagename = $slug .'-'. $currentDate .'-'. uniqid() .'.'. $image->getClientOriginalExtension();

            if (!file_exists('uploads/slider')){
                mkdir('uploads/slider', 0777, true);
            }
            if (fileExists('uploads/slider/'.$slider->image)){
                unlink('uploads/slider/'.$slider->image);
            }

            $image->move('uploads/slider', $imagename);
        }else {
            $imagename = $slider->image;
        }

        $slider->title = $request->title;
        $slider->sub_title = $request->sub_title;
        $slider->image = $imagename;
        $slider->save();
        return redirect(route('slider.index'))->with('successMsg', 'Slider Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider = Slider::find($id);

        if (file_exists('uploads/slider/'.$slider->image)){
            unlink('uploads/slider/'.$slider->image);
            $slider->delete();
        }
        return back()->with('successMsg', 'Slider Successfully Deleted');
    }
}

resources/views/admin/slider/create.blade.php
@extends('layouts.app')


@section('site-title', 'Add New Slider')


@push('css')

@endpush

@section('main-content')

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                @include('layouts.partials.msg')

                    <div class="card">
                        <div class="card-header card-header-info">
                            <h4 class="card-title ">Add New Slider</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('slider.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf

                                <div class="form-group mb-5">
                                    <label for="title">{{ __('Title') }}</label>
                                    <input type="text" name="title"
                                           class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" id="title"
                                           value="{{ old('title') }}" placeholder="Enter your title" required>
                                </div>

                                <div class="form-group mb-5">
                                    <label for="sub_title">{{ __('Sub Title') }}</label>
                                    <input type="text" name="sub_title"
                                           class="form-control{{ $errors->has('sub_title') ? ' is-invalid' : '' }}" id="sub_title"
                                           value="{{ old('sub_title') }}" placeholder="Enter your sub title" required>
                                </div>

                                <div class="mb-5">
                                    <input type="file" name="image" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" id="image" required>
                                </div>

                                <a class="btn btn-danger" href="{{ route('slider.index') }}">{{ __('Back') }}</a>
                                    <button type="submit" class="btn btn-info">{{ __('Submit') }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection


@push('js')

@endpush

resources/views/admin/slider/edit.blade.php
@extends('layouts.app')


@section('site-title', 'Edit Slider')


@push('css')

@endpush

@section('main-content')

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    @include('layouts.partials.msg')

                    <div class="card">
                        <div class="card-header card-header-info">
                            <h4 class="card-title ">Edit Slider</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('slider.update', $slider->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group mb-5">
                                    <label for="title">{{ __('Title') }}</label>
                                    <input type="text" name="title"
                                           class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" id="title"
                                           value="{{ $slider->title }}" placeholder="Enter your title" required>
                                </div>

                                <div class="form-group mb-5">
                                    <label for="sub_title">{{ __('Sub Title') }}</label>
                                    <input type="text" name="sub_title"
                                           class="form-control{{ $errors->has('sub_title') ? ' is-invalid' : '' }}" id="sub_title"
                                           value="{{ $slider->sub_title }}" placeholder="Enter your sub title" required>
                                </div>

                                <div class="mb-5">
                                    <input type="file" name="image" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" id="image" required>
                                </div>

                                <a class="btn btn-danger" href="{{ route('slider.index') }}">{{ __('Back') }}</a>
                                    <button type="submit" class="btn btn-info">{{ __('Submit') }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection


@push('js')

@endpush

resources/views/admin/slider/index.blade.php
@extends('layouts.app')


@section('site-title', 'Slider')


@push('css')

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

@endpush

@section('main-content')

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-info" href="{{ route('slider.create') }}">{{ __('Add New') }}</a>

                    @include('layouts.partials.msg')
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">All Sliders</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="table" class="table table-striped table-bordered" style="width: 100%">
                                    <thead class="text-primary">
                                    <th style="width: 8%">ID</th>
                                    <th>Title</th>
                                    <th>Sub Title</th>
                                    <th>Image</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Action</th>
                                    </thead>
                                    <tbody>
                                        @foreach($sliders as $key=>$slider)
                                            <tr>
                                                <td>{{++$key}}</td>
                                                <td>{{$slider->title}}</td>
                                                <td>{{$slider->sub_title}}</td>
                                                <td>
                                                    <img class="img-responsive img-thumbnail" height="100" width="100" src="{{ asset('uploads/slider/'.$slider->image) }}" alt="{{ $slider->title }}">
                                                </td>
                                                <td>{{$slider->created_at}}</td>
                                                <td>{{$slider->updated_at}}</td>
                                                <td>
                                                    <a class="btn btn-info" href="{{route('slider.edit', $slider->id)}}"><i class="material-icons"> edit  </i></a>
                                                    <button onclick="deleteSlider({{ $slider->id  }})" type="button" class="btn btn-danger"><i class="material-icons">delete</i></button>
                                                    <form action="{{ route('slider.destroy', $slider->id) }}" method="POST" id="delete-form-{{ $slider->id }}" style="display: none;">
                                                        @csrf
                                                        @method('DELETE')
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection


@push('js')
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#table').DataTable();
        } );
    </script>

    <!-- Sweet Alert 2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8.3.0/dist/sweetalert2.all.min.js"></script>
    <!-- Sweet Alert 2 End -->


    <script type="text/javascript">
        function deleteSlider(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You want to delete this slider!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>

@endpush